### PR TITLE
add infra provisioning to DevOps Career portion

### PR DESCRIPTION
**Pull request by matthewzhaocc**
Seems like the DevOps Career is missing a mention for infrastructure provisioning tool, it only mentions configuration tools, though not sure if adding cloud specific tools (CFN, ARM, Deployment Manager) is a good choice

### CODE REVIEW

**Comment by Dreadstar22** [comment]
Those cloud specific tools would be covered under item #1. The only third party tool I can think of is Terraform that is widely adopted. These lists are the basics you'll need to get into the role. Terraform would be a "next step" that people should be able to figure out on their own once they get into that position.

**Comment by matthewzhaocc** [comment]
fair enough, will close PR

**Comment by neilthecellist** [comment]
Reopening briefly. I will say that we are starting to see Pulumi and Google CDM (Cloud Deployment Manager) adoption even in inland territories like Utah and Kentucky. So I would make the case that Terraform is no longer the defacto 3rd-party infrastructure provisioning tool. I'd put it under cloud but DevOps could work too. In fact, I had a client refuse to onboard a candidate because that DevOps Engineer candidate lacked Pulumi experience at the time.

**Comment by Dreadstar22** [comment]
Id still say those belong in the next step. That list under DevOps is the bare minimum you should strive for. You could create a Next Step section under DevOps and put "nice to have but not required" with asterisks in fine print and list all those if you want Matthew.

**Comment by Dreadstar22** [comment]
ARM, GDM, CFN would still fall under #1 though.

**Comment by matthewzhaocc** [comment]
added a beyond the basic portion, also threw in some CICD stuff to make it less empty, oh wait forgot jenkins

**Comment by matthewzhaocc** [comment]
nvm I didn't forgot jenkins, I just have such terrible memory that  I forgot I added something and thought I didn't

**Pull request merged**
